spring:
  active:
    profile: dev   
  application:
    name: employee-app
  datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: mysql
        url: jdbc:mysql://localhost:3306/microservice
        username: root
  addressService:
    base:
      url: http://localhost:8081/address-app/api
